export { AnalysisProcedure } from './analysis-procedure.vo';
export { Email } from './email.vo';
export { EntityId } from './entity-id.vo';
export { Name } from './name.vo';
export { NRLId, NRL_ID_VALUE } from './nrl-id.vo';
export { PLZ } from './plz.vo';
export { ServerConfig } from './server-config.vo';
export { AVVCatalog } from './avvcatalog.vo';
export { ZomoPlan } from './zomo-plan.vo';
export { SearchAlias } from './search-alias.vo';
export { ValueObject, ValueObjectProps } from './value-object';
